### ISSUE TITLE
Uncaught Error: Cannot find module 'moment'

### ISSUE THREAD

**Issue by hyperh** [awsp/handsontable-meteor-1.3-react#1]
I cloned this repo and when I tried to run it it gave me the error:

```
modules-runtime.js?hash=939c79d…:95 Uncaught Error: Cannot find module 'moment'
```

**Comment by hyperh** [comment]
Fix is described here:
https://github.com/handsontable/handsontable/issues/3407#issuecomment-210876728

**Comment by awsp** [comment]
Thanks for the fix! I have updated the repo with fixes.
